#!/bin/bash
# Copyright (C) 2021 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uechos=(
"uecho"
"uecho-rs"
"uecho-go"
"uecho-py"
)

########################################
# Clone
########################################

for n in {0..3}
do
    uechodir=${uechos[$n]}
    rm -rf ${uechodir}
    giturl="https://github.com/cybergarage/${uechos[$n]}"
	git clone ${giturl}
done

########################################
# Benchmark
########################################

build_cmds=(
"./bootstrap && ./configure --enable-examples && make -j 20"
"cargo build"
"make install"
"pip3 install -r requirements.txt"
)

run_cmds=(
"./examples/controller/uechosearch/unix/uechosearch -v"
"cargo run"
"~/go/bin/uechosearch"
"env PYTHONPATH=`pwd` bin/uechosearch -v"
)

for n in {0..3}
do     
    uechodir=${uechos[$n]}
	pushd ${uechodir}
	eval ${build_cmds[$n]}
    # run_cmd="time repeat 5 {${run_cmds[$n]}}"
    run_cmd="time for n in {1..5}; do ${run_cmds[$n]}}; done"
	eval ${run_cmd}
    popd
done
