#!/bin/bash

uechos=(
"uecho"
"uecho-rs"
"uecho-go"
"uecho-py"
)

build_cmds=(
"./bootstrap && ./configure --enable-examples && make -j 20"
"cargo build"
"make install"
"pip3 install -r requirements.txt"
)

run_cmds=(
"time ./examples/controller/uechosearch/unix/uechosearch -v"
"time cargo run"
"~/go/bin/uechosearch"
"env PYTHONPATH=`pwd` bin/uechosearch -v"
)

for n in {0..3}
do
    uechodir=${uechos[$n]}
    giturl="https://github.com/cybergarage/${uechos[$n]}"
	git clone ${giturl}
	pushd ${uechodir}
	eval ${build_cmds[$n]}
	eval ${run_cmds[$n]}
    rm -rf ${uechodir}
    popd
done