#!/bin/bash
# Copyright (C) 2021 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

uechos=(
"uecho"
"uecho-rs"
"uecho-go"
"uecho-py"
)

########################################
# Clone
########################################

for n in {0..3}
do
    uechodir=${uechos[$n]}
    rm -rf ${uechodir}
    giturl="https://github.com/cybergarage/${uechos[$n]}"
	git clone ${giturl}
done

########################################
# LOC (tokei)
########################################

find_rm_cmds=(
"find . -name \"*.cpp\" | xargs -L 1 rm"
"find . -name \"*_test.rs\" | xargs -L 1 rm"
"find . -name \"*_test.go\" | xargs -L 1 rm"
"find . -name \"*_test.py\" | xargs -L 1 rm"
)


rm_cmds=(
"rm src/uecho/std/manufacturers.c src/uecho/std/objects_mra.c"
"rm src/database_manufacturers.rs src/database_mra_objects.rs"
"rm net/echonet/std_manufacturers.go net/echonet/std_mra_objects.go"
"rm uecho/std/manufacturers.py uecho/std/objects_mra.py uecho/std/objects_scsl.py"
)

for n in {0..3}
do
    uechodir=${uechos[$n]}
	pushd ${uechodir}
	eval ${find_rm_cmds[$n]}
    popd
    tokei ${uechodir}
	pushd ${uechodir}
	eval ${rm_cmds[$n]}
    popd
    tokei ${uechodir}
done
