#!/bin/bash

uechos=(
"uecho"
"uecho-rs"
"uecho-go"
"uecho-py"
)

########################################
# Clone
########################################

for n in {0..3}
do
    uechodir=${uechos[$n]}
    rm -rf ${uechodir}
    giturl="https://github.com/cybergarage/${uechos[$n]}"
	git clone ${giturl}
done

########################################
# Benchmark
########################################

build_cmds=(
"./bootstrap && ./configure --enable-examples && make -j 20"
"cargo build"
"make install"
"pip3 install -r requirements.txt"
)

run_cmds=(
"time ./examples/controller/uechosearch/unix/uechosearch -v"
"time cargo run"
"time ~/go/bin/uechosearch"
"time env PYTHONPATH=`pwd` bin/uechosearch -v"
)

for n in {0..3}
do
    uechodir=${uechos[$n]}
	pushd ${uechodir}
	eval ${build_cmds[$n]}
	eval ${run_cmds[$n]}
    popd
done

########################################
# LOC (tokei)
########################################

rm_cmds=(
"rm src/std/manufacturers.c src/std/objects_mra.c"
"rm src/database_manufacturers.rs src/database_mra_objects.rs"
"rm net/echonet/database_manufacturers.go net/echonet/database_mra_objects.go"
"rm uecho/std/manufacturers.py uecho/std/objects_mra.py uecho/std/objects_scsl.py"
)

find_rm_cmds=(
"find . -name "*.cpp" | xargs -L 1 rm"
"find . -name "*_test.rs" | xargs -L 1 rm"
"find . -name "*_test.go" | xargs -L 1 rm"
"find . -name "*_test.py" | xargs -L 1 rm"
)

for n in {0..3}
do
    uechodir=${uechos[$n]}
    tokei ${uechodir}
	pushd ${uechodir}
	eval ${rm_cmds[$n]}
	eval ${find_rm_cmds[$n]}
    popd
    tokei ${uechodir}
done
